# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

   
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
   env_1 : env_test001

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: My CI
    outputs:
      checkout_done: ${{ steps.checkout.outputs.checkout_done }}
      upload_done:   ${{ steps.check.outputs.checkout_done }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "this is env=${{ env.env_1 }}"

      - name: test1
        id: step2
        run: |
         echo "ENV_2=test0001">> $GITHUB_ENV
         sh uploadtest/test.sh
     #   if: steps.checkout_done.outcome == 'success'

      - id: upload
        uses: actions/upload-artifact@v3
        with:
         name: aaaa
         path: uploadtest

        

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: | 
          echo "${{ (steps.checkout.outcome) }}"
          echo "last is env=${{ env.env_1 }}"
          echo "last2 is env=$ENV_2"
          echo "branch name=${{ github.ref.name }}"
       # echo Add other actions to build,
       # echo test, and deploy your project.
       # echo "checkout_done=CheckOut ${{ (steps.checkout.outcome == 'SUCESS') }}"
      
